site_name: grebakker
site_url: https://github.com/dkrajzew/grebakker
site_description: greyrat's simple blog system.
site_author: Daniel Krajzewicz
docs_dir: ./docs

repo_url: https://github.com/dkrajzew/grebakker.git
edit_uri: ""

theme:
    name: material
    custom_dir: ./docs/materials_ext
    font: false
    palette:
        primary: red

extra_css:
    - stylesheets/extra.css
    - stylesheets/prism.css

extra_javascript:
    - js/prism.js

nav:
    - Home: index.md
    - Installation: install.md
    - Usage: usage.md
    - Command Line: cmd.md
    - Links: links.md
    - ChangeLog: changes.md
    - License (GPL): license.md
    - Glossary: glossary.md
    - API: api_grebakker.md
    - Legal: legal.md

exclude_docs:

markdown_extensions:
    - admonition
    - sane_lists

copyright: "&copy; Copyright 2025, Daniel Krajzewicz."

use_directory_urls: false

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [./grebakker]
                options:
                    filters: [""]
                    show_source: False
                    docstring_style: "google"